# NumPy Getting Started

### Installation of NumPy
If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
Install it using this command:

<code>C:\Users\Your Name>pip install numpy</code>

If this command fails, then use a python distribution that already has NumPy installed like, Anaconda, Spyder etc.

### Import NumPy

Once NumPy is installed, import it in your applications by adding the import keyword:

import numpy

Now NumPy is imported and ready to use.

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### NumPy as np

NumPy is usually imported under the np alias

alias: In Python alias are an alternate name for referring to the same thing.
Create an alias with the as keyword while importing:

<code>import numpy as np</code>

Now the NumPy package can be referred to as np instead of numpy.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Checking NumPy Version

The version string is stored under __version__ attribute.

In [3]:
import numpy as np

print(np.__version__)

1.21.5


## NumPy Creating Arrays

### Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called **ndarray**.

We can create a NumPy ndarray object by using the array() function.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
# Use a tuple to create a NumPy array:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

**nested array: are arrays that have arrays as their elements.**